### ISSUE TITLE
Missing licence

### ISSUE THREAD

**Issue by nilsbandel** [viktor-shmigol/electron-windows-badge#1]
The package currently does not seem to currently have a licence. According to https://choosealicense.com/no-permission/ a missing licence generally means "you have no permission from the creators of the software to use, modify, or share the software"

If you intend the package to be open source and usable by others, an MIT licence or similar would be nice.

Great work by the way! 👍😄

**Comment by viktor-shmigol** [comment]
@nilsbandel Thanks for letting me know about it. I've done it.

**Comment by nilsbandel** [comment]
Nice! 😄
