### ISSUE TITLE
Error using badge in angular embedded app

### ISSUE THREAD

**Issue by kespinosa05** [viktor-shmigol/electron-windows-badge#4]
Hi i am get error using this plugin inside ipcRenderer in embedded angular7 app
i am using like that 
`this.electronService.ipcRenderer.sendSync('update-badge', 5);`
and i get error
![image](https://user-images.githubusercontent.com/15805567/52279595-f0af6280-2927-11e9-9914-d205e7a7016e.png)

**Comment by viktor-shmigol** [comment]
@kespinosa05 Have you passed window object to Badge class?
E.g:
```
    function createWindow () {
        win = new BrowserWindow({width: 800, height: 600});
        const badgeOptions = {}
        new Badge(win, badgeOptions);
    }
```
