### ISSUE TITLE
It just not work.

### ISSUE THREAD

**Issue by ntvinhit** [viktor-shmigol/electron-windows-badge#6]
Yep, I do everything in the instruction, recheck for a day, it still not works.

There's no error, just nothing happened.

I don't know if this because of my Windows version or something!?

**Comment by viktor-shmigol** [comment]
@ntvinhit Could you please provide me more information like: OS, electron version etc. It would be helpful to send me link to your repo.

**Comment by ntvinhit** [comment]
@viktor-shmigol 
I'm using Windows 10 latest version, with latest Electron version too.

And I realize that my taskbar is in small icon mode so the overlay will not be shown.

You should write a notice about that problem in README file.

Thank you. My issue is solved.

**Comment by viktor-shmigol** [comment]
Sounds good. Will do
