### ISSUE TITLE
Badge is killed on close event

### ISSUE THREAD

**Issue by imornar** [viktor-shmigol/electron-windows-badge#7]
Hi, this is not really bug but wanted your help/thoughts on how to solve one issue I'm facing.

It'a interesting one, my client requested to override windows closing mechanism to mimic mac OSX behaviour (on X press don't close app - just minimize it). After I done that on first minimize/restore event'a badge stops working since inside lib mainWindow it's set to null on close event.

Some dirty workaround it to recreate it on restore event but I'm not happy with it.

Do you guys have in plan to support this use case? Maybe we can provide one flag within opts which will be responsible to setting this.win to null or not?

let me know what do you think.

**Comment by MatheusMS01** [comment]
I'm having the exactly same problem. Wouldn't it be better to set it to null on 'close**d**' event?

**Comment by vincentpalcon** [comment]
Yup same like skype when you click the X button it will hide only the app.. unless you quit on the taskbar.. What i did is temporary remove the code below under index.js

> // this.win.on('close', () => { this.win = null; });

**Comment by viktor-shmigol** [comment]
Fixed https://github.com/viktor-shmigol/electron-windows-badge/pull/9
